version: '3'
   services:
     sonarqube:
       image: sonarqube:latest
       ports:
         - "9000:9000"
       networks:
         - sonar-net

     scanner:
       image: sonarsource/sonar-scanner-cli:latest
       volumes:
         - .:/app
       working_dir: /app
       command: sonar-scanner
       networks:
         - sonar-net

   networks:
     sonar-net:
       driver: bridge

# services:
#   sonarqube:
#     image: sonarqube:lts
#     container_name: sonarqube
#     ports:
#       - "9000:9000"
#     volumes:
#       - sonarqube_data:/opt/sonarqube/data
#       - sonarqube_extensions:/opt/sonarqube/extensions
#     environment:
#       - SONARQUBE_JDBC_USERNAME=sonar
#       - SONARQUBE_JDBC_PASSWORD=sonar
# volumes:
#   sonarqube_data:
#   sonarqube_extensions: