name: Tests and Conditional Workflow

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      success-percent: ${{ steps.calculate-success.outputs.percentage }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.x

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run tests and save output
      run: bun test | tee test-output.txt

    - name: Verify test output
      run: |
        ls -la test-output.txt
        cat test-output.txt

    - name: Calculate success percentage
      id: calculate-success
      run: |
        python <<EOF
        import re
        with open('test-output.txt') as f:
            output = f.read()
        
        print(f"Output content: {output}")  # Debug: Affiche le contenu du fichier
        
        match = re.search(r'(\d+) passed(?:, (\d+) failed)?', output)
        if match:
            passed = int(match.group(1))
            failed = int(match.group(2)) if match.group(2) else 0
            total = passed + failed
            if total > 0:
                percent = (passed / total) * 100
                print(f"Percentage: {percent:.2f}%")
                with open(env.GITHUB_OUTPUT, 'a') as f:
                    f.write(f"percentage={percent:.2f}\n")
            else:
                print("No tests were executed")
                exit(1)
        else:
            print("No test results found. Check the output format.")
            print(f"Expected format: 'X passed, Y failed'")
            exit(1)
        EOF

  trigger-fly-deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    if: ${{ needs.run-tests.outputs.success-percent >= 40.00 }}
    permissions:
      contents: read
      actions: read
    steps:
      - name: Trigger Fly Deploy workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.actions.createWorkflowDispatch({
              owner: github.repository_owner,
              repo: github.repository,
              workflow_id: "fly-deploy-dev.yml",
              ref: "main",
              inputs: {}
            })