name: Tests and Conditional Workflow

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ steps.test-results.outputs.passed }}
      failed: ${{ steps.test-results.outputs.failed }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run tests and get results
      id: test-results
      run: |
        # Capture la sortie même en cas d'échec
        bun run test 2>&1 | tee test-output.txt || true
        
        # Extraction des résultats avec regex améliorée
        passed=$(grep -oE '[0-9]+ passed' test-output.txt | grep -oE '[0-9]+' || echo "0")
        failed=$(grep -oE '[0-9]+ failed' test-output.txt | grep -oE '[0-9]+' || echo "0")

        # Validation finale
        [ -z "$passed" ] && passed=0
        [ -z "$failed" ] && failed=0
        
        echo "passed=$passed" >> $GITHUB_OUTPUT
        echo "failed=$failed" >> $GITHUB_OUTPUT

        # Debug
        echo "Raw test output:"
        cat test-output.txt
        echo "Parsed values - Passed: $passed, Failed: $failed"

  trigger-fly-deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        id: check-results
        env:
          PASSED: ${{ needs.run-tests.outputs.passed }}
          FAILED: ${{ needs.run-tests.outputs.failed }}
        run: |
          # Conversion en nombres avec valeurs par défaut
          passed=${PASSED:-0}
          failed=${FAILED:-0}
          total=$((passed + failed))
          
          if [ $total -eq 0 ]; then
            echo "::warning::Aucun test détecté - Vérifiez:"
            echo "1. Que les tests existent bien"
            echo "2. Que la sortie des tests contient 'passed'/'failed'"
            echo "3. Le format de sortie de 'bun test'"
            echo "success=false" >> $GITHUB_OUTPUT
          else
            percent=$(( (passed * 100) / total ))
            echo "Percentage: $percent% (${passed}/${total})"
            
            if [ $percent -ge 40 ]; then
              echo "success=true" >> $GITHUB_OUTPUT
            else
              echo "success=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Trigger Fly Deploy workflow
        if: steps.check-results.outputs.success == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "fly-deploy-dev.yml",
              ref: "${{ github.ref }}",
              inputs: {}
            })