name: Tests and Conditional Workflow

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.x

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run tests and get results
      run: |
        bun run test | tee test-output.txt
        # Extract test results from bun test output
        passed=$(grep -oE '(\d+) passed' test-output.txt | awk -F ' ' '{print $1}')
        failed=$(grep -oE '(\d+) failed' test-output.txt | awk -F ' ' '{print $1}')
        
        echo "passed=$passed" >> $GITHUB_OUTPUT
        echo "failed=$failed" >> $GITHUB_OUTPUT

  trigger-fly-deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        id: check-results
        run: |
          if (( $((${needs.run-tests.outputs.passed} * 100 / (${needs.run-tests.outputs.passed} + ${needs.run-tests.outputs.failed}))) >= 40 )); then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT

      - name: Trigger Fly Deploy workflow
        if: steps.check-results.outputs.success == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.actions.createWorkflowDispatch({
              owner: github.repository_owner,
              repo: github.repository,
              workflow_id: "fly-deploy-dev.yml",
              ref: "main",
              inputs: {}
            })