name: Tests and Conditional Workflow

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ steps.test-results.outputs.passed }}
      failed: ${{ steps.test-results.outputs.failed }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run tests and get results
      id: test-results
      run: |
        # Exécute les tests même en cas d'échec
        bun run test || true | tee test-output.txt
        
        # Extraction des résultats avec valeurs par défaut
        passed=$(grep -oP '\d+(?= passed)' test-output.txt | tail -1 || echo "0")
        failed=$(grep -oP '\d+(?= failed)' test-output.txt | tail -1 || echo "0")
        
        # Validation des nombres
        if ! [[ "$passed" =~ ^[0-9]+$ ]]; then passed=0; fi
        if ! [[ "$failed" =~ ^[0-9]+$ ]]; then failed=0; fi
        
        echo "passed=$passed" >> $GITHUB_OUTPUT
        echo "failed=$failed" >> $GITHUB_OUTPUT
        
        # Debug
        echo "Tests passed: $passed"
        echo "Tests failed: $failed"

  trigger-fly-deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        id: check-results
        env:
          PASSED: ${{ needs.run-tests.outputs.passed }}
          FAILED: ${{ needs.run-tests.outputs.failed }}
        run: |
          # Convertit en nombres
          passed=${PASSED:-0}
          failed=${FAILED:-0}
          total=$((passed + failed))
          
          if [ $total -eq 0 ]; then
            echo "::warning::Aucun test détecté - vérifiez la sortie des tests"
            echo "success=false" >> $GITHUB_OUTPUT
            exit 0  # Continue le workflow sans échouer
          else
            percent=$(( (passed * 100) / total ))
            echo "Success percentage: $percent%"
            
            if [ $percent -ge 40 ]; then
              echo "success=true" >> $GITHUB_OUTPUT
            else
              echo "success=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Trigger Fly Deploy workflow
        if: steps.check-results.outputs.success == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "fly-deploy-dev.yml",
              ref: "${{ github.ref }}",
              inputs: {}
            })