name: Tests and Deployment

on: [push, pull_request]

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  ADMIN_ID: ${{ secrets.ADMIN_ID }}
  DUMMY_ID: ${{ secrets.DUMMY_ID }}
  DUMMY2_ID: ${{ secrets.DUMMY2_ID }}
  WRONG_ID: ${{ secrets.WRONG_ID }}

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun run test

  deploy:
    name: Trigger Deployment
    needs: unit-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: '${{ github.ref }}'
            })